usb_cam:
  ros__parameters:
    video_device: "/dev/video4"
    framerate: 30.0
    io_method: "mmap"
    frame_id: "ir_camera"
    pixel_format: "yuyv"
    av_device_format: "YUV422P"
    image_widht: 640
    image_height: 512
    camera_name: "ir_cam"
    # camera_info_url: "package://usb_cam/config/camera_info.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
    auto_white_balance: true
    white_balance: 4000
    autoexposure: true
    exposure: 100
    autofocus: false
    focus: -1